// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    alphabet: 'abcdefghijklmnopqrstuvwxyz' + 'åäöø',
    languages: [
      {
        name: 'swedish',
        capitalized: 'Swedish',
        iso: 'sv',
        wordlists: [{
          id: 'dict',
          name: 'dictionary',
          capitalized: 'Dictionary'
        }]
      }, {
        name: 'english',
        capitalized: 'English',
        iso: 'en',
        wordlists: [
          {
            id: 'dict',
            name: 'dictionary',
            capitalized: 'Dictionary'
          }, {
            id: 'wiki',
            name: 'wikipedia',
            capitalized: 'Wikipedia'
          }
        ]
      }, {
        name: 'spanish',
        capitalized: 'Spanish',
        iso: 'es',
        wordlists: [{
          id: 'dict',
          name: 'dictionary',
          capitalized: 'Dictionary'
        }]
      }, {
        name: 'finnish',
        capitalized: 'Finnish',
        iso: 'fi',
        wordlists: [{
          id: 'dict',
          name: 'dictionary',
          capitalized: 'Dictionary'
        }]
      }
    ]
  };
}).call(this);
