// Generated by LiveScript 1.2.0
(function(){
  var express, http, finder, languages, static_dir, homepage, app;
  express = require('express');
  http = require('http');
  finder = require('./anagram.js');
  languages = require('./languages.js');
  static_dir = './static';
  homepage = static_dir + '/html/index.html';
  app = express();
  app.use(express['static'](static_dir));
  app.get('/', function(req, res){
    return res.sendfile(homepage);
  });
  app.get('/api/anagrams/:langcode/:wordlists/:word', function(req, res){
    var langcode, word, wordlists;
    langcode = req.param('langcode');
    word = req.param('word');
    wordlists = req.param('wordlists');
    return finder.get_anagrams(word, wordlists, langcode, function(anagrams){
      return res.send(anagrams);
    });
  });
  app.get('/api/anagrams/:language/:wordlists', function(req, res){
    return res.send([]);
  });
  app.get('/api/languages', function(req, res){
    return res.send(languages);
  });
  app.listen(process.env.PORT || 8000);
}).call(this);
